config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /users/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}
    
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

    ###topの設定
root to: 'public/homes#top'

 #publicの設定
scope module: :public do
    get '/about' => 'homes#about'
    get 'search' => 'homes#search', as: 'search'
    get '/privacy_policy' => 'homes#privacy_policy', as: 'privacy_policy'
    get '/terms' => 'homes#terms', as: 'terms'
    get '/guideline' => 'homes#guideline', as: 'guideline'
    
    post '/guest', to: 'guest_sessions#create'
    get '/users/my' => 'users#my', as: 'my_page'
    get '/users/infomation/edit' => 'users#edit', as: 'users_edit'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw'


    resources :users, :posts, :details, :address, :my do
      collection do
        get :notifications
      end
    end
    resources :users, only: [:show,:index,:edit,:update] do
      member do
        get :favorites
      end
    end
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    end
end
       

  #adminの設定
  namespace :admin do
  
  root to: '/admin/homes#top'
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :post_comments, only: [:create, :destroy] 
    end
    resources :users, :categories, :posts, :details
    get '/users/:id/posts', to: 'user/posts#index', as: 'user_posts' 
    
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many_attached :images
  validates :title, presence: true
  validates :text, presence: true,length:{maximum:200}
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # has_many :notifications, dependent: :destroy
    def self.search(search) #self.はUser.を意味する
      if search
         where(['text LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
      else
         all #全て表示させる
      end
    end
    
    def favorited_by?(user)
      favorites.exists?(user_id: user.id)
    end
  has_one_attached :profile_image
    def get_profile_image(hight, width)
      unless profile_image.attached?
        file_path = Rails.root.join('app/assets/images/sample.jpg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      profile_image.variant(resize_to_limit: [hight, width]).processed
    end
    
     # 公開・非公開機能
  scope :published, -> {where(is_published_flag: true)}
  scope :unpublished, -> {where(is_published_flag: false)}
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
 
  def index
    @posts = Post.all
    @post = @posts
    @now = Time.now
    
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @now = Time.now
    @user_id = @post.user_id
    
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
  end

  def update
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    user_id = @post.user_id
    @post.destroy
    redirect_to admin_user_posts_path(user_id)
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :text, :category_id, images: []) #categoryを追加
  end
  
end

app/controllers/admin/user/posts_controller.rb
class Admin::User::PostsController < AdminController
 
  def index
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(4)
    # @post = @posts
    @now = Time.now
  end

  # def show
  #   @post = Post.find(params[:id])
  #   @now = Time.now
  # end

  # def edit
  #   @post = Post.find(params[:id])
  # end

  # def create
  #   @post = Post.new(post_params)
  #   @post.user = current_user
  # end

  # def update
  #   @post = Post.find(params[:id])
  # end

  # def destroy
  #   @post = Post.find(params[:id])
  #   @post.destroy
  # end
  
  # private
  
  # def post_params
  #   params.require(:post).permit(:title, :text, :category_id, images: []) #categoryを追加
  # end
  
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/edit.html.erb
<h1>Admin::Posts#edit</h1>
<p>Find me in app/views/admin/posts/edit.html.erb</p>

app/views/admin/posts/new.html.erb
<h1>Admin::Posts#new</h1>
<p>Find me in app/views/admin/posts/new.html.erb</p>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= flash[:notice] %>
      <h4><%= @post.user.name %></h4>
        <p><%= @post.title %></p>
         <p><%= simple_format(@post.text) %></p>
         
            <% if @post.images.attached? %>
              <% @post.images.each do |image| %>
                <%= image_tag image, width: '70%', height: '70%' %>
              <% end %>
            <% end %>
              <p>
                <% if ((@now - @post.created_at).floor / 60) < 60 %>
                  <%= ((@now - @post.created_at).floor / 60) %>分前
                <% elsif ((@now - @post.created_at).floor / 3600) < 24 %>
                  <%= ((@now - @post.created_at).floor / 3600) %>時間前
                <% else %>
                  <%= ((@now - @post.created_at).floor / 86400) %>日前
                <% end %>
              </p>
          
                  <%= link_to admin_post_path(@post.id), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn delete-btn" do %>
                    削除
                  <% end %>
                
    </div>
    
    <div class="col-md-6">
     <h5>コメント一覧</h5>
      <% @post.post_comments.each do |post_comment| %>
        <p><%= image_tag post_comment.user.get_profile_image(50,50), class: "rounded-circle" %></p>
          <p><%= simple_format(post_comment.comment) %></p>
            <p><%= post_comment.user.name %></p>
              <p>
                <% if ((@now - post_comment.created_at).floor / 60) < 60 %>
                  <%= ((@now - post_comment.created_at).floor / 60) %>分前
                <% elsif ((@now - post_comment.created_at).floor / 3600) < 24 %>
                  <%= ((@now - post_comment.created_at).floor / 3600) %>時間前
                <% else %>
                  <%= ((@now - post_comment.created_at).floor / 86400) %>日前
                <% end %>
              </p>
                <%= link_to admin_post_post_comment_path(post_comment.post_id, post_comment.id), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn delete-btn" do %>
                  削除
                <% end %>
      <% end %>
      
        <p>コメント件数：<%= @post.post_comments.count %>件</p>
        <div class="form-group">
          <div class="row">
            <div class="col-md-4 d-md-flex">
              <%= link_to admin_user_posts_path(@user_id), class: "btn send-btn" do %>
                投稿一覧
              <% end %>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>