config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /users/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}
    
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

    ###topの設定
root to: 'public/homes#top'

 #publicの設定
scope module: :public do
    get '/about' => 'homes#about'
    get 'search' => 'homes#search', as: 'search'
    get '/privacy_policy' => 'homes#privacy_policy', as: 'privacy_policy'
    get '/terms' => 'homes#terms', as: 'terms'
    get '/guideline' => 'homes#guideline', as: 'guideline'
    
    post '/guest', to: 'guest_sessions#create'
    get '/users/my' => 'users#my', as: 'my_page'
    get '/users/infomation/edit' => 'users#edit', as: 'users_edit'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw'


    resources :users, :posts, :details, :address, :my do
      collection do
        get :notifications
      end
    end
    resources :users, only: [:show,:index,:edit,:update] do
      member do
        get :favorites
      end
    end
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    end
end
       

  #adminの設定
  namespace :admin do
  
  root to: '/admin/homes#top'
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :post_comments, only: [:create, :destroy] 
    end
    resources :users, :categories, :posts, :details
    get '/users/:id/posts', to: 'user/posts#index', as: 'user_posts' 
    
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  def get_profile_image(hight, width)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [hight, width]).processed
  end
  
  validates :name,presence: true
  validates :email, presence: true
  validates :address, presence: true
 
  
  has_many :posts
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :notifications, dependent: :destroy
  has_many :notification_comments, through: :notifications, source: :post_comment
  
  def unread_notifications
    self.notifications.unread
  end
  def unread_notification_comments
    Commeent.where(id: self.notifications.unread.pluck(:post_comment_id))
  end
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def is_guest?
    self.email == guest_email
  end
  
  enum address: { 
    "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
    
  }
  
  private
  
  def guest_email
    "guest@example.com"
  end
end

app/controllers/admin/user/posts_controller.rb
class Admin::User::PostsController < AdminController
 
  def index
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(4)
    # @post = @posts
    @now = Time.now
  end

  # def show
  #   @post = Post.find(params[:id])
  #   @now = Time.now
  # end

  # def edit
  #   @post = Post.find(params[:id])
  # end

  # def create
  #   @post = Post.new(post_params)
  #   @post.user = current_user
  # end

  # def update
  #   @post = Post.find(params[:id])
  # end

  # def destroy
  #   @post = Post.find(params[:id])
  #   @post.destroy
  # end
  
  # private
  
  # def post_params
  #   params.require(:post).permit(:title, :text, :category_id, images: []) #categoryを追加
  # end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
 

  def index
    @user = User.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to admin_users_path
    else
      render :edit
    end
    
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :encrypted_password, :address, :is_deleted)
  end
  
  # def is_matching_login_user
  #   user = User.find(params[:id])
  #   unless user.id == current_user.id
  #     redirect_to root_path
  #   end
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row offset-md-1">
    <div class="col-md-8 offset-md-1">
      <h4><%= @user.name %>さんの会員情報編集</h4>
      <%= form_with model: @user, url: admin_user_path, method: :patch do |f| %>
        <div class="form-group">
          <div class="row">
            <div class="col-md-10 d-md-flex">
              <div class="col-5 offset-md-1"><%= f.label "会員ID" %></div>
                <div class="col-md-7"><%= @user.id %></div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-4 offset-md-1"><%= f.label "名前" %></div>
              <div class="col-3"><%= f.text_field :name, :size => "30", class: "text-box" %></div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-4 offset-md-1"><%= f.label "お住いの都道府県" %></div>
            <div class="col-3"><%= f.select :address, User.addresses.keys, {}, style: "color: #bf7fff" %></div>
          </div>
        </div>
        
        <div class="form-group">
          <div class="row">
            <div class="col-4 offset-md-1"><%= f.label "メールアドレス" %></div>
            <div class="col-2"><%= f.email_field :email, :size => "30", class: "text-box" %></div>
          </div>
        </div>
        
        <div class="form-group">
          <div class="row">
            <div class="col-4 offset-md-1"><%= f.label "会員ステータス" %></div>
            <div class="col-4"><%= f.radio_button :is_deleted, :false %><%= f.label "有効" %>
            <%= f.radio_button :is_deleted, true %><%= f.label "退会" %></div>
          </div>
        </div>

        <div class="actions">
          <%= f.submit '編集内容を保存する', class:"btn edit-btn" %>
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="containe">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto offset-sm-1">
      <h2>会員一覧</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>都道府県</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%=link_to user.name, admin_user_path(user.id) %></td>
            <td><%= user.email %></td>
            <td><%= user.address %></td>
            <% if user.is_deleted %>
                <td class="text-secondary font-weight-bold">無効</td>
              <% else %>
                <td class="text-success font-weight-bold">有効</td>
              <% end %>
          </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<h1>Admin::Users#new</h1>
<p>Find me in app/views/admin/users/new.html.erb</p>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 offset-md-3">
      <h4><%= @user.name %>さんの会員詳細</h4>
      <%= form_with model: @user, url: admin_users_path, method: :post do |f| %>
        <div class="form-group">
          <div class="row">
            <div class="col-md-12 d-md-flex">
              <div class="field col-md-5"><%= f.label "会員ID" %></div>
                <div class="col-md-7"><%= @user.id %></div>
              </div>
            </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-md-12 d-md-flex">
              <div class="field col-md-5"><%= f.label "ユーザー名" %></div>
                <div class="col-md-7"><%= @user.name %></div>
            </div>
           </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-md-12 d-md-flex">
              <div class="field col-md-5"><%= f.label "メールアドレス" %></div>
                <div class="col-md-7"><%= @user.email %></div>
            </div>
          </div>
        </div>
        
        <div class="form-group">
          <div class="row">
            <div class="col-md-12 d-md-flex">
              <div class="field col-md-5"><%= f.label "都道府県" %></div>
                <div class="col-md-7"><%= @user.address %></div>
            </div>
          </div>
        </div>
        
        <div class="form-group">
          <div class="row">
            <div class="col-md-12 d-md-flex">
              <div class="field col-md-5"><%= f.label "会員ステータス" %></div>
                <div class="col-md-7">
                  <% if @user.is_deleted %>
                    <div class="text-secondary">無効</div>
                  <% else %>
                    <div class="text-success">有効</div>
                  <% end %>
                </div>
            </div>
          </div>
        </div>
      <% end %>
      
        <div class="form-group">
          <div class="row">
            <div class="col-md-2 d-md-flex">
              <%= link_to  edit_admin_user_path(@user.id), class: "btn edit-btn" do %>
                編集する
              <% end %>
            </div>
            <div class="col-md-3 d-md-flex">
              <%= link_to admin_user_posts_path, class: "btn send-btn" do %>
                投稿一覧
              <% end %>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>