config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /users/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}
    
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

    ###topの設定
root to: 'public/homes#top'

 #publicの設定
scope module: :public do
    get '/about' => 'homes#about'
    get 'search' => 'homes#search', as: 'search'
    get '/privacy_policy' => 'homes#privacy_policy', as: 'privacy_policy'
    get '/terms' => 'homes#terms', as: 'terms'
    get '/guideline' => 'homes#guideline', as: 'guideline'
    
    post '/guest', to: 'guest_sessions#create'
    get '/users/my' => 'users#my', as: 'my_page'
    get '/users/infomation/edit' => 'users#edit', as: 'users_edit'
    get '/users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/withdraw' => 'users#withdraw', as: 'withdraw'


    resources :users, :posts, :details, :address, :my do
      collection do
        get :notifications
      end
    end
    resources :users, only: [:show,:index,:edit,:update] do
      member do
        get :favorites
      end
    end
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
    end
end
       

  #adminの設定
  namespace :admin do
  
  root to: '/admin/homes#top'
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :post_comments, only: [:create, :destroy] 
    end
    resources :users, :categories, :posts, :details
    get '/users/:id/posts', to: 'user/posts#index', as: 'user_posts' 
    
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :post_comment
  
  scope :unread, -> { where( already_read: false ) }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many_attached :images
  validates :title, presence: true
  validates :text, presence: true,length:{maximum:200}
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # has_many :notifications, dependent: :destroy
    def self.search(search) #self.はUser.を意味する
      if search
         where(['text LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
      else
         all #全て表示させる
      end
    end
    
    def favorited_by?(user)
      favorites.exists?(user_id: user.id)
    end
  has_one_attached :profile_image
    def get_profile_image(hight, width)
      unless profile_image.attached?
        file_path = Rails.root.join('app/assets/images/sample.jpg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
      profile_image.variant(resize_to_limit: [hight, width]).processed
    end
    
     # 公開・非公開機能
  scope :published, -> {where(is_published_flag: true)}
  scope :unpublished, -> {where(is_published_flag: false)}
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true,length:{maximum:140}
  has_many :notifications, dependent: :destroy
  
  after_save do
    Notification.create!(user_id: self.post.user.id, post_comment_id: self.id)
    ContactMailer.send_notification(self.post.user, self).deliver #確認メールを送信
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  def get_profile_image(hight, width)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [hight, width]).processed
  end
  
  validates :name,presence: true
  validates :email, presence: true
  validates :address, presence: true
 
  
  has_many :posts
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :notifications, dependent: :destroy
  has_many :notification_comments, through: :notifications, source: :post_comment
  
  def unread_notifications
    self.notifications.unread
  end
  def unread_notification_comments
    Commeent.where(id: self.notifications.unread.pluck(:post_comment_id))
  end
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  def is_guest?
    self.email == guest_email
  end
  
  enum address: { 
    "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
    
  }
  
  private
  
  def guest_email
    "guest@example.com"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :authenticate_admin!
    # before_action :configure_permitted_parameters, if: :devise_controller?
    # before_action :is_matching_login_user, only: [:edit, :update]
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])
  end
  
  def log_in(user)
    session[:user_id] = user.id
  end
    
  def update
   contact = Contact.find(params[:id]) #contact_mailer.rbの引数を指定
   contact.update(contact_params)
   user = contact.user
   ContactMailer.send_when_admin_reply(user, contact).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    #before_action :authenticate_user!, except: [:top]
    #before_action :configure_permitted_parameters, if: :devise_controller?
    # before_action :is_matching_login_user, only: [:edit, :update]
  
  protected

  #def configure_permitted_parameters
  #  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])
  #end
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # before_action :set_user

  def reject_user
    @user = User.find_by(name: params[:user][:name])
    if @user 
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/guest_sessions_helper.rb
module GuestSessionsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>Ayame</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
          <%= csrf_meta_tags %>
          <%= csp_meta_tag %>
          
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic&display=swap" rel="stylesheet">
          <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
          <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
          <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="header">
      <div class="jumbotron">　
        <nav class="navbar navbar-expand-lg ">
          <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <% if !current_user.is_guest? %>
                  <li class="nav-item">
                    <%= link_to '新規投稿', new_post_path, style: "color: #674196", class: 'nav-link font-weight-bold' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'マイページ',  my_page_path, style: "color: #674196", class: 'nav-link font-weight-bold' %>
                  </li>
                <% end %>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_user_session_path, style: "color: #674196", method: :delete, class: 'nav-link font-weight-bold' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to notifications_users_path, style: "color: #ffb366", class: 'nav-link font-weight-bold' do %>
                      <i class="fas fa-bell"></i>
                    <% end %>
                  </li>
                
              <% elsif admin_signed_in? %>
                
                <li class="nav-item">
                  <%= link_to '会員一覧', admin_root_path, style: "color: #674196", class: 'nav-link font-weight-bold' %>
                </li>
                
                <li class="nav-item">
                  <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, style: "color: #674196", class: 'nav-link font-weight-bold' %>
                </li>
              
              <% else %>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, style: "color: #674196", class: 'nav-link font-weight-bold' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, style: "color: #674196", class: 'nav-link font-weight-bold' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'ゲストユーザー', guest_path, style: "color: #674196", method: :post, class: 'nav-link font-weight-bold' %>
                </li>

              <% end %>
              </ul>
            </div>
          </div>
        </nav>
      <div class="container">
        <h1><%= link_to "あやめ", root_path, style: "color: #6A5ACD", class: 'nav-link font-weight-bold d-inline' %></h1>
        <p>ひとり親の方が笑顔になるコミュニティサイト</p>
      </div>
    </div>
    </header>
    <main class="m-5">
    <%= yield %>
    </main>
    <footer>
      <div class="headwrap">
      <div class="container text- pt-5 pb-4">
        <div class="row no-gutters">
          <div class="col-md-9">
           
           
      
          </div>
          <div class="col-md-3">
            <table>
            <tr class="p-0 list-unstyled">
              <td>
                <%= link_to privacy_policy_path, style: "color: #87CEFA", class: "nav-link" do %>
                  <h3 title="プライバシーポリシー"><i class="fas fa-lock"></i></h3>
                <% end %>
              </td>
              <td>
                <%= link_to terms_path, style: "color: #87CEFA", class: "nav-link" do %>
                  <h3 title="利用規約"><i class="fas fa-file"></i></h3>
                <% end %>
              </td>
              
            </tr>
            </table>
          </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>